use std::{collections::{HashMap, VecDeque}, hash::Hash, path::PathBuf, sync::{Arc, Mutex, atomic::AtomicUsize}};
use ospl_common::{ast::{Expr, Expression, LV, LValue, Literal, Position, Statement, Stmt, decl::Declaration}, inst::{optimized::Inst, symbols::DebugSymbolTable}};
use ospl_compiler::{BuildData, Compiler};

use crate::{BUILD_FOLDER, Log, graph::resolv0::{PkgRef, VersionRuleRef}};

#[derive(Clone)]
pub struct CxxNode {
    pub required_as: String,
    pub o_file: PathBuf,
    pub c_file: PathBuf,
    pub link_with: Vec<String>,
}

pub type ModuleId = u32;

#[derive(Default, Debug)]
pub struct Graph {
    pub modules: HashMap<ModuleId, ModuleNode>,
    
    /// The ID of the program entrypoint
    pub main: ModuleId,
}

#[derive(Default)]
pub struct ModuleNode {
    pub deps: Vec<Requirement>,
    pub cxx_deps: Vec<CxxNode>,
    pub ast: Vec<Statement>,

    /// Uused for anything but logging
    pub meta: ModuleNodeMeta
}

#[derive(Default)]
pub struct ModuleNodeMeta {
    pub name: String,
    pub pkg: String,
}

impl std::fmt::Debug for ModuleNode {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        return write!(f, "{}/{}", self.meta.pkg, self.meta.name)
    }
}

#[derive(Clone, Default, Debug)]
pub struct Requirement {
    pub ident: String,
    pub id: u32,
}

#[derive(Clone, Debug)]
pub struct UnresolvedRequirement {
    pub re: PkgRef,
    pub ver: VersionRuleRef
}

/// Generated modules repr
pub struct GennedMods {
    pub mapping: HashMap<u32, GeneratedModule>,
    pub root: Vec<Statement>,
}

/// Generates the AST for every module. It puts every module as a function
/// inside of `root`. Imports take the form `#PKG/MODULE#`. Here is an example
/// AST generated by this function:
/// ```ospl,norun
/// def "#example/A#" = fn() -> scope {
///     def add = fn(x:int y:int) -> int {
///         return x + y
///     }
/// 
///     return scope
/// }
/// 
/// ***** required as 'example/A' as 'A' *****
/// def "#example/B#" = fn["#example/A#"]() -> scope {
///     def A = "#example/A"
///     def subtract = fn(x:int y:int) -> int {
///         return x - y
///     }
/// 
///     def WHATS_NINE_PLUS_TEN = A.add(9  10)  # "uhh, 21?"
/// 
///     return scope
/// }
/// ```
pub fn genmods(graph: &Graph) -> GennedMods {
    let keys: Vec<u32> = graph.modules.keys().cloned().collect();
    let order = topo_sort(
        &keys,
        |id| graph.modules[id].deps.iter().map(|e| e.id).collect(),
    ).expect("cycle in dependency graph!");

    let mut finished: HashMap<u32, GeneratedModule> = HashMap::new();

    let mut root = Vec::new();

    for node_id in order {
        let node = &graph.modules[&node_id];
        let node_global_id = format!("#{}/{}#", node.meta.pkg, node.meta.name);
        let filepath = Arc::new(node_global_id.clone());

        // generate the list of captures and new input code
        let mut new_input_code = Vec::new();
        let mut captures = Vec::new();
        for req in &node.deps {
            let req_global_ident = finished[&req.id].global_ident.clone();
            captures.push(req_global_ident.clone());

            // pushs code like `def IMPORT_NAME = REQ_GLOBAL_IDENT`
            // to allow the user to access it by import name rather than global name
            new_input_code.push(Statement {
                at: Position::default(),
                file: filepath.clone(),
                notes: String::new(),
                inner: Box::new(Stmt::Define(Declaration {
                    name: req.ident.clone(),
                    rhs: Expression {
                        at: Position::default(),
                        file: filepath.clone(),
                        inner: Box::new(Expr::LValue(LValue {
                            at: Position::default(),
                            file: filepath.clone(),
                            inner: Box::new(LV::Variable(req_global_ident.clone()))
                        }))
                    }
                })),
            });
        }

        // add any CXX dependencies
        for cxx_req in &node.cxx_deps {
            new_input_code.push(Statement {
                at: Position::default(),
                file: filepath.clone(),
                notes: String::new(),
                inner: Box::new(Stmt::Define(Declaration {
                    name: cxx_req.required_as.clone(),
                    rhs: Expression {
                        at: Position::default(),
                        file: filepath.clone(),
                        inner: Box::new(Expr::FFILoad(Expression {
                            at: Position::default(),
                            file: filepath.clone(),
                            inner: Box::new(Expr::Literal(Literal::Str(
                                cxx_req.o_file.with_added_extension("so").to_string_lossy().to_string()
                            )))
                        }))
                    }
                })),
            });
        }

        // add the previous input code to the new one so that declarations are
        // at the start of the new code
        new_input_code.extend(node.ast.clone());

        // use the new input code in the declaration
        let wrapped_ast = super::wrap_in_iife_declaration(
            &node_global_id,
            &captures,
            new_input_code.clone(),
            filepath.clone()
        );

        // add this to the root as well
        root.push(wrapped_ast.clone());

        // finish up this one
        finished.insert(node_id, GeneratedModule {
            file: node_global_id.clone(),
            cxx_deps: node.cxx_deps.clone(),
            deps: node.deps.clone(),
            stmts: new_input_code,
            global_ident: node_global_id,
        });
        root.push(wrapped_ast);
    }

    return GennedMods {
        mapping: finished,
        root,
    };
}

#[derive(Clone)]
pub struct GeneratedModule {
    pub stmts: Vec<Statement>,
    pub file: String,
    pub cxx_deps: Vec<CxxNode>,
    pub deps: Vec<Requirement>,
    pub global_ident: String
}

pub fn buildmain(graph: &Graph, m: GennedMods) -> Result<Vec<Inst>, ospl_compiler::CE> {
    for (_, every_node) in &m.mapping {
        for cxx in &every_node.cxx_deps {
            Log!(Invoking, "C compiler on {:?}", cxx.c_file);
            let mut so_file2 = PathBuf::from(BUILD_FOLDER);
            so_file2.push(cxx.o_file.with_extension("so"));

            let mut obj_file2 = PathBuf::from(BUILD_FOLDER);
            obj_file2.push(cxx.o_file.with_extension("o"));

            if !std::process::Command::new("cc")
                .arg("-fPIC")
                .arg("-c")
                .arg(&cxx.c_file)
                .arg("-o")
                .arg(&obj_file2)
                .spawn()
                .expect("failed to summon cc")
                .wait()
                .expect("failed to wait for cc")
                .success()
            { panic!("CC failed to run") }

            if !std::process::Command::new("cc")
                .arg("-shared")
                .arg(obj_file2)
                .arg("-o")
                .arg(&so_file2)
                .spawn()
                .expect("failed to summon cc")
                .wait()
                .expect("failed to wait for cc")
                .success()
            { panic!("CC failed to run") }
        };
    }

    let build_data = Arc::new(BuildData {
        next_resource_id: AtomicUsize::new(0),
        symbols: Mutex::new(DebugSymbolTable::default())
    });

    Log!(Compiling, "everything");
    let mut comp = Compiler::new(build_data);
    let mut root = Vec::new();
    comp.compile_all(&m.root, &mut root)?;

    return Ok(root)
}

/// Generic topological sort using Kahn's algorithm.
///
/// nodes:
///   - all graph nodes
///
/// edges:
///   - function returning dependencies for a node
///
/// Returns:
///   - `Some(sorted list)` if DAG
///   - `None` if cycle exists
pub fn topo_sort<N, F>(nodes: &[N], mut edges: F) -> Option<Vec<N>>
where
    N: Eq + Hash + Clone,
    F: FnMut(&N) -> Vec<N>,
{
    let mut indegree: HashMap<N, usize> = HashMap::new();
    let mut adj: HashMap<N, Vec<N>> = HashMap::new();

    // initialize graph
    for node in nodes {
        indegree.entry(node.clone()).or_insert(0);

        for dep in edges(node) {
            adj.entry(dep.clone()).or_default().push(node.clone());
            *indegree.entry(node.clone()).or_insert(0) += 1;
        }
    }

    // queue of nodes with no incoming edges
    let mut q = VecDeque::new();
    for (node, &deg) in &indegree {
        if deg == 0 {
            q.push_back(node.clone());
        }
    }

    let mut result = Vec::with_capacity(nodes.len());

    while let Some(n) = q.pop_front() {
        result.push(n.clone());

        if let Some(children) = adj.get(&n) {
            for c in children {
                let entry = indegree.get_mut(c).unwrap();
                *entry -= 1;

                if *entry == 0 {
                    q.push_back(c.clone());
                }
            }
        }
    }

    if result.len() == nodes.len() {
        Some(result)
    } else {
        None // cycle detected
    }
}